# Generated by Django 4.2.4 on 2023-08-20 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ("name",),
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
            },
        ),
    ]
